In [1]:
import pandas as pd

In [20]:
df = pd.read_csv('Titanic.csv')

In [9]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [12]:
df.drop(["PassengerId","Name","Ticket"],axis=1,inplace=True)

KeyError: "['PassengerId', 'Name', 'Ticket'] not found in axis"

In [11]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

In [13]:
DROP_COLS = [ "PassengerId","Name","Ticket"]

In [17]:
def drop_cols(df,cols):
    return df.drop(cols,axis=1)

In [21]:
df = drop_cols(df,DROP_COLS)

In [22]:
df

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0           0       3    male  22.0      1      0   7.2500   NaN        S
1           1       1  female  38.0      1      0  71.2833   C85        C
2           1       3  female  26.0      0      0   7.9250   NaN        S
3           1       1  female  35.0      1      0  53.1000  C123        S
4           0       3    male  35.0      0      0   8.0500   NaN        S
..        ...     ...     ...   ...    ...    ...      ...   ...      ...
886         0       2    male  27.0      0      0  13.0000   NaN        S
887         1       1  female  19.0      0      0  30.0000   B42        S
888         0       3  female   NaN      1      2  23.4500   NaN        S
889         1       1    male  26.0      0      0  30.0000  C148        C
890         0       3    male  32.0      0      0   7.7500   NaN        Q

[891 rows x 9 columns]

In [24]:
df.dtypes

Survived      int64
Pclass        int64
Sex             str
Age         float64
SibSp         int64
Parch         int64
Fare        float64
Cabin           str
Embarked        str
dtype: object

In [49]:
dtype = df.dtypes
n_uniq= df.nunique()
print(dtype)
pd.DataFrame({"Dtypes ":dtype,"N_uniques ":n_uniq})

Survived    category
Pclass      category
Sex         category
Age          float64
SibSp       category
Parch       category
Fare         float64
Embarked    category
dtype: object

           Dtypes   N_uniques
Survived  category           2
Pclass    category           3
Sex       category           2
Age        float64          88
SibSp     category           7
Parch     category           7
Fare       float64         247
Embarked  category           3

In [ ]:
cols = ["Survived","Pclass","Sex","SibSp","Parch","Embarked"]
df[cols] = df[cols].astype("category")
x = pd.DataFrame(df.dtypes)
x.to_csv("aa.csv")

In [50]:
null = df.isnull().sum()
ratio = null / df.shape[0] * 100
pd.DataFrame({"null ":null, "ratio ":ratio})

          null   ratio
Survived      0     0.0
Pclass        0     0.0
Sex           0     0.0
Age           0     0.0
SibSp         0     0.0
Parch         0     0.0
Fare          0     0.0
Embarked      0     0.0

In [39]:
df = df.dropna(subset = ['Embarked'])

In [41]:
df = df.drop("Cabin",axis =1)

In [42]:
df

    Survived Pclass     Sex   Age SibSp Parch     Fare Embarked
0          0      3    male  22.0     1     0   7.2500        S
1          1      1  female  38.0     1     0  71.2833        C
2          1      3  female  26.0     0     0   7.9250        S
3          1      1  female  35.0     1     0  53.1000        S
4          0      3    male  35.0     0     0   8.0500        S
..       ...    ...     ...   ...   ...   ...      ...      ...
886        0      2    male  27.0     0     0  13.0000        S
887        1      1  female  19.0     0     0  30.0000        S
888        0      3  female   NaN     1     2  23.4500        S
889        1      1    male  26.0     0     0  30.0000        C
890        0      3    male  32.0     0     0   7.7500        Q

[889 rows x 8 columns]

In [43]:
df.describe()

              Age        Fare
count  712.000000  889.000000
mean    29.642093   32.096681
std     14.492933   49.697504
min      0.420000    0.000000
25%     20.000000    7.895800
50%     28.000000   14.454200
75%     38.000000   31.000000
max     80.000000  512.329200

In [ ]:
median = df['Age'].median()
median
df["Age"] = df['Age'].fillna(median)

In [ ]:
num_cols = df.select_dtypes("number").columns
for col in num_cols:
    Q1 = df[col].quantile(.25)
    Q3 = df[col].quantile(.75)
    IQR = Q3-Q1
    lower_fence = Q1-(1.5)*IQR
    upper_fence = Q3+(1.5)*IQR

    lower_outliers = df[df[col]<lower_fence][col].values
    print(upper_outliers)

    upper_outliers = df[df[col]>upper_fence][col].values
    print(upper_outliers)

[]
[58.  55.  66.  65.  59.  71.  70.5 55.5 61.  56.  58.  59.  62.  58.
 63.  65.  61.  60.  64.  65.  56.  63.  58.  55.  71.  64.  62.  62.
 60.  61.  57.  80.  56.  58.  70.  60.  60.  70.  57.  74.  56. ]
[58.  55.  66.  65.  59.  71.  70.5 55.5 61.  56.  58.  59.  62.  58.
 63.  65.  61.  60.  64.  65.  56.  63.  58.  55.  71.  64.  62.  62.
 60.  61.  57.  80.  56.  58.  70.  60.  60.  70.  57.  74.  56. ]
[ 71.2833 263.     146.5208  82.1708  76.7292  83.475   73.5    263.
  77.2875 247.5208  73.5     77.2875  79.2     66.6     69.55    69.55
 146.5208  69.55   113.275   76.2917  90.      83.475   90.      79.2
  86.5    512.3292  79.65   153.4625 135.6333  77.9583  78.85    91.0792
 151.55   247.5208 151.55   110.8833 108.9     83.1583 262.375  164.8667
 134.5     69.55   135.6333 153.4625 133.65    66.6    134.5    263.
  75.25    69.3    135.6333  82.1708 211.5    227.525   73.5    120.
 113.275   90.     120.     263.      81.8583  89.1042  91.0792  90.
  78.2667 151.55    86.5    108.9     93.5    221.7792 106.425   71.
 106.425  110.8833 227.525   79.65   110.8833  79.65    79.2     78.2667
 153.4625  77.9583  69.3     76.7292  73.5    113.275  133.65    73.5
 512.3292  76.7292 211.3375 110.8833 227.525  151.55   227.525  211.3375
 512.3292  78.85   262.375   71.      86.5    120.      77.9583 211.3375
  79.2     69.55   120.      93.5     83.1583  69.55    89.1042 164.8667
  69.55    83.1583]