In [3]:
import numpy as np
np.random.random((3,3))

array([[0.30788156, 0.45286389, 0.97343104],
       [0.18770354, 0.63441637, 0.45303104],
       [0.9746286 , 0.78501909, 0.04466901]])

In [5]:
np.random.randint(0,1000,(5,5))

array([[764, 401, 349, 689,  94],
       [485, 330, 488, 372, 610],
       [570, 172, 609, 350, 437],
       [245,  12, 489,  50, 241],
       [951, 562, 354, 930,  38]], dtype=int32)

In [6]:
a = ["ali",3,"omar",True]
np.random.choice(a,size=(3,3))

array([['True', 'ali', 'ali'],
       ['True', 'True', 'omar'],
       ['ali', '3', 'omar']], dtype='<U21')

In [7]:
Mat1 = np.ones((3,4))
Mat2 = np.zeros((5,3))
np.savez('matrices.npz',Mat1,Mat2)

In [8]:
with np.load('matrices.npz') as file:
    Mat1 = file['arr_0']
    Mat2 = file['arr_1']
    print(Mat1)
    print("="*10)
    print(Mat2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
==========
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

In [10]:
v = np.array([1,3,4,5,0])
print(np.all(v>=1))

False

In [12]:
v = np.array([1,3,4,5,0])
print(np.any(v==1))

True

In [13]:
v1 = np.array([1,3,4,5,0])
v2 = np.array([2,3,0,5,3])
np.isclose(v1,v2,atol=1)

array([ True,  True, False,  True, False])

In [ ]:
v1 = np.array([1,3,4,5,0])
v2 = np.array([2,3,0,5,3])
np.allclose(v1,v2,atol=1)

In [20]:
v = np.array([2,3,4,5])
condition = v>=4
print(condition)
v[condition]=-1
print(v)
print(v+3)

[False False  True  True]
[ 2  3 -1 -1]
[5 6 2 2]

In [29]:
import pandas as pd
s = pd.Series([1,2,3,4],index=['A','B','C','D'])
print(s)
print(type(s))

A    1
B    2
C    3
D    4
dtype: int64
<class 'pandas.Series'>

In [31]:
data = [[1,444,"abc"],
        [2,555,"def"],
        [3,666,"ghi"],
        [4,444,"xyz"]]
df = pd.DataFrame(data,columns=['col1','col2','col3'])
df.head()

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [ ]:
df.describe(include = 'category')

           col1        col2
count  4.000000    4.000000
mean   2.500000  527.250000
std    1.290994  106.274409
min    1.000000  444.000000
25%    1.750000  444.000000
50%    2.500000  499.500000
75%    3.250000  582.750000
max    4.000000  666.000000

In [34]:
df['col2'].min()

np.int64(444)

In [38]:
df.col2.value_counts()

col2
444    2
555    1
666    1
Name: count, dtype: int64

In [39]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    4 non-null      int64
 1   col2    4 non-null      int64
 2   col3    4 non-null      str
dtypes: int64(2), str(1)
memory usage: 228.0 bytes